version: '3'

services:
  app:
    build:
      context: node
    container_name: node-nginx-app
    volumes:
      - ./node:/app
      - /app/node_modules
    networks:
      - node-network
    tty: true
    restart: always
    ports:
      - "3000:3000"
    depends_on:
       - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: node-nginx-db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

  nginx:
    build:
      context: nginx
    container_name: node-nginx
    networks:
      - node-network
    ports: 
      - "8080:80"
    depends_on:
      - app
  
networks: 
  node-network:
    driver: bridge
